
curl --request POST  --url 
curl --request GET  --url  
curl --request PUT  --url  
curl --request PATCH  --url 
curl --request DELETE  --url  
curl --request OPTIONS --url 
curl --request TRACE --url  
curl --request HEAD --url  
curl --request ACL   --url  
curl --request BASELINE-CONTROL   --url 
curl --request BIND   --url  
curl --request CHECKIN	  --url  
curl --request RFC3253  --ur 
curl --request CHECKOUT  --url  
curl --request RFC3253  --url  
curl --request COPY  --url  
curl --request LABEL  --url  
curl --request LINK  --url  
curl --request LOCK  --url  
curl --request MERGE  --url  
curl --request MKACTIVITY  --url 
curl --request MKCALENDAR  --url  
curl --request MKCOL  --url  
curl --request MKREDIRECTREF  --url  
curl --request MKWORKSPACE  --url  
curl --request MOVE  --url 
curl --request ORDERPATCH  --url 
curl --request PATCH  --url  
curl --request RFC5789 --url  
curl --request PROPFIND   --url  
curl --request PROPPATCH   --url  
curl --request REBIND  --url  
curl --request SEARCH  --url    
curl --request UNBIND   --url  
curl --request UNCHECKOUT  --url
curl --request UNLINK   --url
curl --request UNLOCK  --url 
curl --request UPDATE   --url
curl --request UPDATEREDIRECTREF   --url
 update all   
