DirBuster 1.0-RC1 - Report
http://www.owasp.org/index.php/Category:OWASP_DirBuster_Project
Report produced on Fri Aug 05 10:24:03 EDT 2022
--------------------------------

https://www.payoneer.com:443
--------------------------------
Directories found during testing:

Dirs found with a 200 response:

/
/wp-admin/admin-ajax.php/
/wp-admin/admin-functions.php/wp-admin/admin-ajax.php/
/wp-admin/about.php/wp-admin/admin-ajax.php/
/wp-admin/admin-header.php/wp-admin/admin-ajax.php/
/wp-admin/admin-db.php/wp-admin/admin-ajax.php/
/wp-admin/admin-footer.php/wp-admin/admin-ajax.php/
/wp-admin/css/install.css/wp-admin/admin-ajax.php/
/wp-admin/css/ie-rtl.min.css/wp-admin/admin-ajax.php/
/wp-admin/css/ie-rtl.dev.css/wp-admin/admin-ajax.php/
/wp-admin/css/ie.min.css/wp-admin/admin-ajax.php/
/wp-admin/css/ie-rtl.css/wp-admin/admin-ajax.php/
/wp-admin/css/ie.dev.css/wp-admin/admin-ajax.php/
/wp-admin/css/ie.css/wp-admin/admin-ajax.php/
/wp-admin/css/global-rtl.css/wp-admin/admin-ajax.php/
/wp-admin/css/global-rtl.dev.css/wp-admin/admin-ajax.php/
/wp-admin/css/global.dev.css/wp-admin/admin-ajax.php/
/wp-admin/css/global.css/wp-admin/admin-ajax.php/
/wp-admin/css/farbtastic-rtl.css/wp-admin/admin-ajax.php/
/wp-admin/css/dashboard-rtl.dev.css/wp-admin/admin-ajax.php/
/wp-admin/css/dashboard-rtl.css/wp-admin/admin-ajax.php/
/wp-admin/css/farbtastic.css/wp-admin/admin-ajax.php/
/wp-admin/css/dashboard.dev.css/wp-admin/admin-ajax.php/
/wp-admin/css/colors-fresh.min.css/wp-admin/admin-ajax.php/
/wp-admin/css/dashboard.css/wp-admin/admin-ajax.php/
/wp-admin/css/customize-controls-rtl.css/wp-admin/admin-ajax.php/
/wp-admin/css/customize-controls-rtl.min.css/wp-admin/admin-ajax.php/
/wp-admin/css/customize-controls.min.css/wp-admin/admin-ajax.php/
/wp-admin/css/customize-controls.css/wp-admin/admin-ajax.php/
/wp-admin/css/colors-fresh-rtl.dev.css/wp-admin/admin-ajax.php/
/wp-admin/css/colors-fresh-rtl.css/wp-admin/admin-ajax.php/

Dirs found with a 403 response:

/wp-admin/admin-db.php/
/wp-admin/admin-footer.php/
/wp-admin/about.php/
/wp-admin/admin-functions.php/
/wp-admin/admin-header.php/
/wp-admin/admin-post.php/
/wp-admin/categories.js/
/wp-admin/categories.php/
/wp-admin/comment.php/
/wp-admin/async-upload.php/
/wp-admin/admin.php/
/wp-admin/cat.js/
/wp-admin/credits.php/
/wp-admin/bookmarklet.php/
/wp-json/wp/v2/users/
/wp-admin/css/color-picker.min.css/
/wp-admin/css/color-picker-rtl.css/
/wp-admin/css/color-picker-rtl.min.css/
/wp-admin/css/color-picker.css/
/wp-admin/css/colors-classic.dev.css/
/wp-admin/css/colors-classic.css/
/wp-admin/css/colors-classic.min.css/
/wp-admin/css/colors-classic-rtl.css/
/wp-admin/css/colors-classic-rtl.dev.css/
/wp-admin/css/colors-fresh.css/
/wp-admin/css/colors-fresh.dev.css/
/wp-admin/css/colors-fresh-rtl.css/
/wp-admin/css/colors-fresh-rtl.dev.css/
/wp-admin/css/colors-fresh.min.css/
/wp-admin/css/customize-controls.css/
/wp-admin/css/customize-controls-rtl.css/
/wp-admin/css/customize-controls-rtl.min.css/
/wp-admin/css/customize-controls.min.css/
/wp-admin/css/dashboard.css/
/wp-admin/css/dashboard.dev.css/
/wp-admin/css/dashboard-rtl.css/
/wp-admin/css/dashboard-rtl.dev.css/
/wp-admin/css/farbtastic.css/
/wp-admin/css/farbtastic-rtl.css/
/wp-admin/css/global.css/
/wp-admin/css/global.dev.css/
/wp-admin/css/global-rtl.dev.css/
/wp-admin/css/global-rtl.css/
/wp-admin/css/ie.css/
/wp-admin/css/ie.dev.css/
/wp-admin/css/ie.min.css/
/wp-admin/css/ie-rtl.css/
/wp-admin/css/ie-rtl.dev.css/
/wp-admin/css/ie-rtl.min.css/
/wp-admin/css/install.css/
/wp-admin/css/install.dev.css/
/wp-admin/css/install.min.css/
/wp-admin/css/install-rtl.css/
/wp-admin/css/install-rtl.dev.css/
/wp-admin/css/login.css/
/wp-admin/css/login.dev.css/
/wp-admin/css/login-rtl.css/
/wp-admin/css/login-rtl.dev.css/
/wp-admin/css/media.css/
/wp-admin/css/media.dev.css/
/wp-admin/css/media.min.css/
/wp-admin/css/media-rtl.css/
/wp-admin/css/media-rtl.dev.css/
/wp-admin/css/media-rtl.min.css/
/wp-admin/css/ms.css/
/wp-admin/css/ms.dev.css/
/wp-admin/css/nav-menu.css/
/wp-admin/css/nav-menu.dev.css/
/wp-admin/css/nav-menu-rtl.css/
/wp-admin/css/nav-menu-rtl.dev.css/
/wp-admin/css/plugin-install.css/
/wp-admin/css/plugin-install.dev.css/
/wp-admin/css/plugin-install-rtl.css/
/wp-admin/css/plugin-install-rtl.dev.css/
/wp-admin/css/press-this.css/
/wp-admin/css/press-this.dev.css/
/wp-admin/css/press-this-rtl.css/
/wp-admin/css/press-this-rtl.dev.css/
/wp-admin/css/theme-editor.css/
/wp-admin/css/theme-editor.dev.css/
/wp-admin/css/theme-editor-rtl.css/
/wp-admin/css/theme-editor-rtl.dev.css/
/wp-admin/css/theme-install.css/
/wp-admin/css/theme-install.dev.css/
/wp-admin/css/widgets.css/
/wp-admin/css/widgets.dev.css/
/wp-admin/css/widgets-rtl.css/
/wp-admin/css/widgets-rtl.dev.css/
/wp-admin/css/wp-admin.css/
/wp-admin/css/wp-admin.dev.css/
/wp-admin/css/wp-admin.min.css/
/wp-admin/css/wp-admin-rtl.css/
/wp-admin/css/wp-admin-rtl.dev.css/
/wp-admin/css/wp-admin-rtl.min.css/
/wp-admin/custom-background.php/
/wp-admin/custom-fields.js/
/wp-admin/custom-header.php/
/enterprise/
/wp-admin/customize.php/
/wp-admin/dbx-admin-key.js/
/es/
/wp-admin/edit-attachment-rows.php/
/wp-admin/edit-category-form.php/
/wp-admin/edit-comments.js/
/wp-admin/edit-comments.php/
/wp-admin/edit-form-advanced.php/
/wp-admin/edit-form-comment.php/
/wp-admin/edit-form.php/
/wp-admin/edit-link-categories.php/
/ja/
/wp-admin/edit-link-category-form.php/
/ar/
/wp-admin/edit-link-form.php/
/ko/
/wp-admin/edit-page-form.php/
/ru/
/wp-admin/edit-pages.php/
/vi/
/wp-admin/edit.php/
/zh/
/wp-admin/edit-post-rows.php/
/ua/
/wp-admin/edit-tag-form.php/
/wp-admin/edit-tags.php/
/th/
/solutions/
/wp-admin/export.php/
/wp-admin/freedoms.php/
/wp-admin/gears-manifest.php/
/p-admin/images/
/wp-admin/images/align-center-2x.png/
/wp-admin/images/align-center.png/
/wp-admin/images/align-left-2x.png/
/wp-admin/images/align-left.png/
/wp-admin/images/align-none-2x.png/
/wp-admin/images/align-none.png/
/wp-admin/images/align-right-2x.png/
/wp-admin/images/align-right.png/
/wp-admin/images/archive-link.png/
/industries/
/wp-admin/images/arrows-2x.png/
/wp-admin/images/arrows-dark-2x.png/
/wp-admin/images/arrows-dark.png/
/wp-admin/images/arrows-dark-vs-2x.png/
/wp-admin/images/arrows-dark-vs.png/
/wp-admin/images/arrows.png/
/wp-admin/images/arrows-pr-2x.png/
/wp-admin/images/arrows-pr.png/
/wp-admin/images/arrows-vs-2x.png/
/resources/
/wp-admin/images/arrows-vs.png/
/wp-admin/images/blue-grad.png/
/partners/
/wp-admin/images/box-bg.gif/
/wp-admin/images/box-bg-left.gif/
/wp-admin/images/box-bg-right.gif/
/wp-admin/images/box-butt.gif/
/wp-admin/images/box-butt-left.gif/
/about/
/wp-admin/images/box-butt-right.gif/
/wp-admin/images/box-head.gif/
/wp-admin/images/box-head-left.gif/
/wp-admin/images/box-head-right.gif/
/careers/
/wp-admin/images/browse-happy.gif/
/wp-admin/images/bubble_bg-2x.gif/
/wp-admin/images/bubble_bg.gif/
/wp-admin/images/bubble_bg-rtl-2x.gif/
/mobile-app/
/wp-admin/images/bubble_bg-rtl.gif/
/wp-admin/images/button-grad-active.png/
/wp-admin/images/button-grad-active-vs.png/
/wp-admin/images/button-grad.png/
/wp-admin/images/button-grad-vs.png/
/legal/
/wp-admin/images/comment-grey-bubble-2x.png/
/wp-admin/images/comment-grey-bubble.png/
/wp-admin/images/date-button-2x.gif/
/wp-admin/images/date-button.gif/
/wp-admin/images/ed-bg.gif/
/customer-disclosures-and-complaints/
/wp-admin/images/ed-bg-vs.gif/
/wp-admin/images/fade-butt.png/
/wp-admin/images/fav-arrow.gif/
/wp-admin/images/fav-arrow-rtl.gif/
/wp-admin/images/fav-arrow-vs.gif/
/wp-admin/images/fav-arrow-vs-rtl.gif/
/wp-admin/images/fav.png/
/wp-admin/images/fav-top-vs.gif/
/wp-content/
/wp-admin/images/fav-vs.png/
/wp-admin/images/generic.png/
/wp-admin/images/gray-grad.png/
/wp-admin/images/icons32-2x.png/
/wp-admin/images/icons32.png/
/wp-admin/images/icons32-vs-2x.png/
/wp-admin/images/icons32-vs.png/
/wp-admin/images/imgedit-icons-2x.png/
/wp-admin/images/imgedit-icons.png/
/wp-admin/images/list-2x.png/
/wp-admin/images/list.png/
/wp-admin/images/list-vs.png/
/wp-admin/images/loading.gif/
/wp-admin/images/loading-publish.gif/
/wp-admin/images/lock-2x.png/
/wp-admin/images/lock.png/
/wp-admin/images/login-bkg-bottom.gif/
/wp-admin/images/login-bkg-tile.gif/
/wp-admin/images/login-header.png/
/wp-admin/images/logo-ghost.png/
/wp-admin/images/logo.gif/
/wp-admin/images/logo-login.gif/
/wp-admin/images/marker.png/
/wp-admin/images/mask.png/
/wp-admin/images/media-button-2x.png/
/wp-admin/images/media-button-image.gif/
/wp-admin/images/media-button-music.gif/
/wp-admin/images/media-button-other.gif/
/wp-admin/images/media-button.png/
/wp-includes/
/wp-admin/images/media-button-video.gif/
/wp-admin/images/menu-2x.png/
/wp-admin/images/menu-arrows.gif/
/wp-admin/images/menu-bits.gif/
/wp-admin/images/menu-bits-rtl.gif/
/wp-admin/images/menu-bits-rtl-vs.gif/
/wp-admin/images/menu-bits-vs.gif/
/wp-admin/images/menu-dark.gif/
/wp-admin/images/menu-dark-rtl.gif/
/wp-admin/images/menu.png/
/wp-admin/images/menu-shadow.png/
/wp-admin/images/menu-shadow-rtl.png/
/wp-admin/images/menu-vs-2x.png/
/wp-admin/images/menu-vs.png/
/wp-admin/images/no.png/
/wp-admin/images/notice.gif/
/wp-admin/images/post-formats32.png/
/wp-admin/images/post-formats32-vs.png/
/wp-admin/images/post-formats.png/
/wp-admin/images/post-formats-vs.png/
/wp-admin/images/press-this-2x.png/
/wp-admin/images/press-this.png/
/wp-admin/images/required.gif/
/wp-admin/images/resize-2x.gif/
/wp-admin/images/resize.gif/
/wp-admin/images/resize-rtl-2x.gif/
/wp-admin/images/resize-rtl.gif/
/wp-admin/images/screen-options-right.gif/
/wp-admin/images/screen-options-right-up.gif/
/wp-admin/images/sort-2x.gif/
/wp-admin/images/se.png/
/wp-admin/images/sort.gif/
/wp-admin/images/star.gif/
/wp-admin/images/stars-2x.png/
/wp-admin/images/stars.png/
/wp-admin/images/stars-rtl-2x.png/
/wp-admin/images/stars-rtl.png/
/wp-admin/images/toggle-arrow.gif/
/wp-admin/images/toggle-arrow-rtl.gif/
/wp-admin/images/toggle.gif/
/wp-admin/images/visit-site-button-grad.gif/
/wp-admin/images/visit-site-button-grad-vs.gif/
/wp-admin/images/welcome-icons-2x.png/
/wp-admin/images/welcome-icons.png/
/wp-admin/images/wheel.png/
/wp-admin/images/white-grad-active.png/
/wp-admin/images/white-grad.png/
/wp-admin/images/widgets-arrow.gif/
/wp-admin/images/wordpress-logo-2x.png/
/wp-admin/images/wp-badge-2x.png/
/wp-admin/images/wordpress-logo.png/
/wp-admin/images/wp-badge.png/
/wp-admin/images/wp-logo-2x.png/
/wp-admin/images/wp-logo.png/
/wp-admin/images/wp-logo-vs-2x.png/
/wp-admin/images/wp-logo-vs.gif/
/wp-admin/images/wp-logo-vs.png/
/wp-admin/images/wpspin_dark.gif/
/wp-admin/images/wpspin_light-2x.gif/
/wp-admin/images/wpspin_light.gif/
/wp-admin/images/xit-2x.gif/
/wp-admin/images/xit.gif/
/wp-admin/images/yes.png/
/wp-admin/import/blogger.php/
/p-admin/import/
/wp-admin/import/blogware.php/
/wp-admin/import/dotclear.php/
/wp-admin/import/greymatter.php/
/wp-admin/import/livejournal.php/
/wp-admin/import/mt.php/
/wp-admin/import.php/
/wp-admin/import/rss.php/
/wp-admin/import/textpattern.php/
/wp-admin/import/wordpress.php/
/p-admin/includes/
/wp-admin/includes/admin.php/
/wp-admin/includes/ajax-actions.php/
/wp-admin/includes/bookmark.php/
/wp-admin/includes/class-ftp.php/
/wp-admin/includes/class-ftp-pure.php/
/wp-admin/includes/class-ftp-sockets.php/
/wp-admin/includes/class-pclzip.php/
/wp-admin/includes/class-wp-comments-list-table.php/
/wp-admin/includes/class-wp-filesystem-base.php/
/wp-admin/includes/class-wp-filesystem-direct.php/
/wp-admin/includes/class-wp-filesystem-ftpext.php/
/wp-admin/includes/class-wp-filesystem-ftpsockets.php/
/wp-admin/includes/class-wp-filesystem-ssh2.php/
/wp-admin/includes/class-wp-importer.php/
/wp-admin/includes/class-wp-links-list-table.php/
/wp-admin/includes/class-wp-list-table.php/
/wp-admin/includes/class-wp-media-list-table.php/
/wp-admin/includes/class-wp-ms-sites-list-table.php/
/wp-admin/includes/class-wp-ms-themes-list-table.php/
/wp-admin/includes/class-wp-ms-users-list-table.php/
/wp-admin/includes/class-wp-plugin-install-list-table.php/
/wp-admin/includes/class-wp-plugins-list-table.php/
/wp-admin/includes/class-wp-posts-list-table.php/
/wp-admin/includes/class-wp-terms-list-table.php/
/wp-admin/includes/class-wp-theme-install-list-table.php/
/wp-admin/includes/class-wp-themes-list-table.php/
/wp-admin/includes/class-wp-upgrader.php/
/wp-admin/includes/class-wp-users-list-table.php/
/wp-admin/includes/comment.php/
/wp-admin/includes/continents-cities.php/
/wp-admin/includes/dashboard.php/
/wp-admin/includes/deprecated.php/
/wp-admin/includes/export.php/
/wp-admin/includes/file.php/
/wp-admin/includes/image-edit.php/
/wp-admin/includes/image.php/
/wp-admin/includes/import.php/
/wp-admin/includes/list-table.php/
/wp-admin/includes/manifest.php/
/wp-admin/includes/media.php/
/wp-admin/includes/menu.php/
/wp-admin/includes/meta-boxes.php/
/wp-admin/includes/misc.php/
/wp-admin/includes/ms-deprecated.php/
/wp-admin/includes/ms.php/
/wp-admin/includes/nav-menu.php/
/wp-admin/includes/plugin-install.php/
/wp-admin/includes/plugin.php/
/wp-admin/includes/post.php/
/wp-admin/includes/revision.php/
/wp-admin/includes/schema.php/
/wp-admin/includes/screen.php/
/wp-admin/includes/taxonomy.php/
/wp-admin/includes/template.php/
/wp-admin/includes/theme-install.php/
/wp-admin/includes/theme.php/
/wp-admin/includes/update-core.php/
/wp-admin/includes/update.php/
/wp-admin/includes/upgrade.php/
/wp-admin/includes/widgets.php/
/wp-admin/includes/user.php/
/wp-admin/index-extra.php/
/wp-admin/index.php/
/wp-admin/install.css/
/wp-admin/install-helper.php/
/wp-admin/install.php/
/wp-admin/install-rtl.css/
/p-admin/js/
/wp-admin/js/accordion.js/
/wp-admin/js/accordion.min.js/
/wp-admin/js/cat.dev.js/
/wp-admin/js/categories.dev.js/
/wp-admin/js/categories.js/
/wp-admin/js/categories.min.js/
/wp-admin/js/cat.js/
/wp-admin/js/cat.min.js/
/wp-admin/js/color-picker.js/
/wp-admin/js/color-picker.min.js/
/wp-admin/js/comment.dev.js/
/wp-admin/js/comment.js/
/wp-admin/js/comment.min.js/
/wp-admin/js/common.dev.js/
/wp-admin/js/common.js/
/wp-admin/js/common.min.js/
/wp-admin/js/custom-background.dev.js/
/wp-admin/js/custom-background.js/
/wp-admin/js/custom-background.min.js/
/wp-admin/js/custom-fields.dev.js/
/wp-admin/js/custom-fields.js/
/wp-admin/js/custom-fields.min.js/
/wp-admin/js/custom-header.js/
/wp-admin/js/customize-controls.js/
/wp-admin/js/customize-controls.min.js/
/wp-admin/js/dashboard.dev.js/
/wp-admin/js/dashboard.js/
/wp-admin/js/edit-comments.dev.js/
/wp-admin/js/dashboard.min.js/
/wp-admin/js/edit-comments.js/
/wp-admin/js/edit-comments.min.js/
/wp-admin/js/editor.dev.js/
/wp-admin/js/editor.js/
/wp-admin/js/editor.min.js/
/wp-admin/js/farbtastic.js/
/wp-admin/js/gallery.dev.js/
/wp-admin/js/gallery.js/
/wp-admin/js/gallery.min.js/
/wp-admin/js/image-edit.dev.js/
/wp-admin/js/image-edit.js/
/wp-admin/js/image-edit.min.js/
/wp-admin/js/inline-edit-post.dev.js/
/wp-admin/js/inline-edit-post.js/
/wp-admin/js/inline-edit-post.min.js/
/wp-admin/js/inline-edit-tax.dev.js/
/wp-admin/js/inline-edit-tax.js/
/wp-admin/js/inline-edit-tax.min.js/
/wp-admin/js/iris.min.js/
/wp-admin/js/link.dev.js/
/wp-admin/js/link.min.js/
/wp-admin/js/link.js/
/wp-admin/js/media.dev.js/
/wp-admin/js/media-gallery.js/
/wp-admin/js/media-gallery.min.js/
/wp-admin/js/media.js/
/wp-admin/js/media.min.js/
/wp-admin/js/media-upload.dev.js/
/wp-admin/js/media-upload.js/
/wp-admin/js/media-upload.min.js/
/wp-admin/js/nav-menu.dev.js/
/wp-admin/js/nav-menu.js/
/wp-admin/js/nav-menu.min.js/
/wp-admin/js/password-strength-meter.dev.js/
/wp-admin/js/password-strength-meter.js/
/wp-admin/js/password-strength-meter.min.js/
/wp-admin/js/plugin-install.dev.js/
/wp-admin/js/plugin-install.js/
/wp-admin/js/plugin-install.min.js/
/wp-admin/js/postbox.dev.js/
/wp-admin/js/postbox.js/
/wp-admin/js/postbox.min.js/
/wp-admin/js/post.dev.js/
/wp-admin/js/post.js/
/wp-admin/js/post.min.js/
/wp-admin/js/revisions.js/
/wp-admin/js/revisions.min.js/
/wp-admin/js/revisions-js.php/
/wp-admin/js/set-post-thumbnail.dev.js/
/wp-admin/js/set-post-thumbnail.js/
/wp-admin/js/set-post-thumbnail.min.js/
/wp-admin/js/tags.dev.js/
/wp-admin/js/tags.js/
/wp-admin/js/tags.min.js/
/wp-admin/js/theme.js/
/wp-admin/js/theme.min.js/
/wp-admin/js/theme-preview.dev.js/
/wp-admin/js/theme-preview.js/
/wp-admin/js/theme-preview.min.js/
/wp-admin/js/user-profile.dev.js/
/wp-admin/js/user-profile.js/
/wp-admin/js/user-profile.min.js/
/wp-admin/js/user-suggest.js/
/wp-admin/js/user-suggest.min.js/
/wp-admin/js/utils.dev.js/
/wp-admin/js/utils.js/
/wp-admin/js/widgets.dev.js/
/wp-admin/js/widgets.js/
/wp-admin/js/widgets.min.js/
/wp-admin/js/word-count.dev.js/
/wp-admin/js/word-count.js/
/wp-admin/js/word-count.min.js/
/wp-admin/js/wp-fullscreen.js/
/wp-admin/js/wp-fullscreen.min.js/
/wp-admin/js/xfn.dev.js/
/wp-admin/js/xfn.js/
/wp-admin/js/xfn.min.js/
/wp-admin/link-add.php/
/wp-admin/link-category.php/
/wp-admin/link-import.php/
/wp-admin/link-manager.php/
/wp-admin/link-parse-opml.php/
/wp-admin/link.php/
/wp-admin/load-styles.php/
/wp-admin/load-scripts.php/
/p-admin/maint/
/wp-admin/maint/repair.php/
/wp-admin/media-new.php/
/wp-admin/media.php/
/wp-admin/media-upload.php/
/wp-admin/menu-header.php/
/wp-admin/menu.php/
/wp-admin/moderation.php/
/wp-admin/ms-edit.php/
/wp-admin/ms-delete-site.php/
/wp-admin/ms-admin.php/
/wp-admin/ms-options.php/
/wp-admin/ms-sites.php/
/wp-admin/ms-themes.php/
/wp-admin/ms-upgrade-network.php/
/wp-admin/ms-users.php/
/wp-admin/my-sites.php/
/wp-admin/nav-menus.php/
/p-admin/network/
/wp-admin/network/admin.php/
/wp-admin/network/about.php/
/wp-admin/network/credits.php/
/wp-admin/network/edit.php/
/wp-admin/network/freedoms.php/
/wp-admin/network/menu.php/
/wp-admin/network/index.php/
/wp-admin/network.php/
/wp-admin/network/plugin-editor.php/
/wp-admin/network/plugin-install.php/
/wp-admin/network/plugins.php/
/wp-admin/network/profile.php/
/wp-admin/network/settings.php/
/wp-admin/network/setup.php/
/wp-admin/network/site-info.php/
/wp-admin/network/site-new.php/
/wp-admin/network/site-settings.php/
/wp-admin/network/sites.php/
/wp-admin/network/site-themes.php/
/wp-admin/network/site-users.php/
/wp-admin/network/theme-editor.php/
/wp-admin/network/theme-install.php/
/wp-admin/network/themes.php/
/wp-admin/network/update-core.php/
/wp-admin/network/update.php/
/wp-admin/network/upgrade.php/
/wp-admin/network/user-edit.php/
/wp-admin/network/user-new.php/
/wp-admin/network/users.php/
/wp-admin/options-discussion.php/
/wp-admin/options-general.php/
/wp-admin/options-media.php/
/wp-admin/options-head.php/
/wp-admin/options-misc.php/
/wp-admin/options-permalink.php/
/wp-admin/options.php/
/wp-admin/options-privacy.php/
/wp-admin/options-reading.php/
/wp-admin/options-writing.php/
/wp-admin/page-new.php/
/wp-admin/page.php/

Dirs found with a 502 response:

/wp-admin/css/farbtastic-rtl.css/wp-admin/includes/user.php/


--------------------------------
Files found during testing:

Files found with a 403 responce:

/wp-admin/cat.js/index.php.php
/wp-admin/cat.js/license.txt.php
/wp-admin/cat.js/readme.html.php
/wp-admin/cat.js/wp-activate.php.php
/wp-admin/cat.js/wp-config.php.stage.php
/wp-admin/cat.js/p-admin.php
/wp-admin/cat.js/wp-admin/about.php.php
/wp-admin/cat.js/wp-admin/admin-ajax.php.php
/wp-admin/cat.js/wp-admin/admin-db.php.php
/wp-admin/cat.js/wp-admin/admin-footer.php.php
/wp-admin/cat.js/wp-admin/admin-functions.php.php
/wp-admin/cat.js/wp-admin/admin-header.php.php
/wp-admin/cat.js/wp-admin/admin.php.php
/wp-admin/cat.js/wp-admin/admin-post.php.php
/wp-admin/cat.js/wp-admin/async-upload.php.php
/wp-admin/cat.js/wp-admin/bookmarklet.php.php
/wp-admin/cat.js/wp-admin/categories.js.php
/wp-admin/cat.js/wp-admin/categories.php.php
/wp-admin/cat.js/wp-admin/cat.js.php
/wp-admin/cat.js/wp-admin/comment.php.php
/wp-admin/cat.js/wp-admin/credits.php.php
/wp-admin/cat.js/p-admin/css.php
/wp-admin/cat.js/p-json.php
/wp-admin/cat.js/wp-json/wp/v2/posts.php
/wp-admin/cat.js/wp-json/wp/v2/users.php
/wp-admin/cat.js/wp-admin/css/color-picker.css.php
/wp-admin/cat.js/wp-admin/css/color-picker.min.css.php
/wp-admin/cat.js/wp-admin/css/color-picker-rtl.css.php
/wp-admin/cat.js/wp-admin/css/color-picker-rtl.min.css.php
/wp-admin/cat.js/wp-admin/css/colors-classic.css.php
/wp-admin/cat.js/wp-admin/css/colors-classic.dev.css.php
/wp-admin/cat.js/wp-admin/css/colors-classic.min.css.php
/wp-admin/cat.js/wp-admin/css/colors-classic-rtl.css.php
/wp-admin/cat.js/wp-admin/css/colors-classic-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/colors-fresh.css.php
/wp-admin/cat.js/wp-admin/css/colors-fresh.dev.css.php
/wp-admin/cat.js/wp-admin/css/colors-fresh.min.css.php
/wp-admin/cat.js/wp-admin/css/colors-fresh-rtl.css.php
/wp-admin/cat.js/wp-admin/css/colors-fresh-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/customize-controls.css.php
/wp-admin/cat.js/wp-admin/css/customize-controls.min.css.php
/wp-admin/cat.js/wp-admin/css/customize-controls-rtl.css.php
/wp-admin/cat.js/wp-admin/css/customize-controls-rtl.min.css.php
/wp-admin/cat.js/wp-admin/css/dashboard.css.php
/wp-admin/cat.js/wp-admin/css/dashboard.dev.css.php
/wp-admin/cat.js/wp-admin/css/dashboard-rtl.css.php
/wp-admin/cat.js/wp-admin/css/dashboard-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/farbtastic.css.php
/wp-admin/cat.js/wp-admin/css/farbtastic-rtl.css.php
/wp-admin/cat.js/wp-admin/css/global.css.php
/wp-admin/cat.js/wp-admin/css/global.dev.css.php
/wp-admin/cat.js/wp-admin/css/global-rtl.css.php
/wp-admin/cat.js/wp-admin/css/global-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/ie.css.php
/wp-admin/cat.js/wp-admin/css/ie.dev.css.php
/wp-admin/cat.js/wp-admin/css/ie.min.css.php
/wp-admin/cat.js/wp-admin/css/ie-rtl.css.php
/wp-admin/cat.js/wp-admin/css/ie-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/ie-rtl.min.css.php
/wp-admin/cat.js/wp-admin/css/install.css.php
/wp-admin/cat.js/wp-admin/css/install.dev.css.php
/wp-admin/cat.js/wp-admin/css/install.min.css.php
/wp-admin/cat.js/wp-admin/css/install-rtl.css.php
/wp-admin/cat.js/wp-admin/css/install-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/login.css.php
/wp-admin/cat.js/wp-admin/css/login.dev.css.php
/wp-admin/cat.js/wp-admin/css/login-rtl.css.php
/wp-admin/cat.js/wp-admin/css/login-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/media.css.php
/wp-admin/cat.js/wp-admin/css/media.min.css.php
/wp-admin/cat.js/wp-admin/css/media.dev.css.php
/wp-admin/cat.js/wp-admin/css/media-rtl.css.php
/wp-admin/cat.js/wp-admin/css/media-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/media-rtl.min.css.php
/wp-admin/cat.js/wp-admin/css/ms.css.php
/wp-admin/cat.js/wp-admin/css/ms.dev.css.php
/wp-admin/cat.js/wp-admin/css/nav-menu.css.php
/wp-admin/cat.js/wp-admin/css/nav-menu.dev.css.php
/wp-admin/cat.js/wp-admin/css/nav-menu-rtl.css.php
/wp-admin/cat.js/wp-admin/css/nav-menu-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/plugin-install.dev.css.php
/wp-admin/cat.js/wp-admin/css/plugin-install.css.php
/wp-admin/cat.js/wp-admin/css/plugin-install-rtl.css.php
/wp-admin/cat.js/wp-admin/css/plugin-install-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/press-this.css.php
/wp-admin/cat.js/wp-admin/css/press-this.dev.css.php
/wp-admin/cat.js/wp-admin/css/press-this-rtl.css.php
/wp-admin/cat.js/wp-admin/css/press-this-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/theme-editor.css.php
/wp-admin/cat.js/wp-admin/css/theme-editor.dev.css.php
/wp-admin/cat.js/wp-admin/css/theme-editor-rtl.css.php
/wp-admin/cat.js/wp-admin/css/theme-editor-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/theme-install.css.php
/wp-admin/cat.js/wp-admin/css/theme-install.dev.css.php
/wp-admin/cat.js/wp-admin/css/widgets.css.php
/wp-admin/cat.js/wp-admin/css/widgets.dev.css.php
/wp-admin/cat.js/wp-admin/css/widgets-rtl.css.php
/wp-admin/cat.js/wp-admin/css/widgets-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/wp-admin.css.php
/wp-admin/cat.js/wp-admin/css/wp-admin.dev.css.php
/wp-admin/cat.js/wp-admin/css/wp-admin.min.css.php
/wp-admin/cat.js/wp-admin/css/wp-admin-rtl.css.php
/wp-admin/cat.js/wp-admin/css/wp-admin-rtl.dev.css.php
/wp-admin/cat.js/wp-admin/css/wp-admin-rtl.min.css.php
/wp-admin/cat.js/wp-admin/custom-background.php.php
/wp-admin/cat.js/wp-admin/custom-fields.js.php
/wp-admin/cat.js/wp-admin/custom-header.php.php
/wp-admin/cat.js/wp-admin/customize.php.php
/wp-admin/cat.js/wp-admin/dbx-admin-key.js.php
/wp-admin/cat.js/wp-admin/edit-attachment-rows.php.php
/wp-admin/cat.js/wp-admin/edit-category-form.php.php
/wp-admin/cat.js/wp-admin/edit-comments.js.php
/wp-admin/cat.js/wp-admin/edit-comments.php.php
/wp-admin/cat.js/wp-admin/edit-form-advanced.php.php
/wp-admin/cat.js/wp-admin/edit-form-comment.php.php
/wp-admin/cat.js/wp-admin/edit-form.php.php
/wp-admin/cat.js/wp-admin/edit-link-categories.php.php
/wp-admin/cat.js/wp-admin/edit-link-category-form.php.php
/wp-admin/cat.js/wp-admin/edit-link-form.php.php
/wp-admin/cat.js/wp-admin/edit-page-form.php.php
/wp-admin/cat.js/wp-admin/edit-pages.php.php
/wp-admin/cat.js/wp-admin/edit.php.php
/wp-admin/cat.js/wp-admin/edit-post-rows.php.php
/wp-admin/cat.js/wp-admin/edit-tag-form.php.php
/wp-admin/cat.js/wp-admin/edit-tags.php.php
/wp-admin/cat.js/wp-admin/export.php.php
/wp-admin/cat.js/wp-admin/freedoms.php.php
/wp-admin/cat.js/wp-admin/gears-manifest.php.php
/wp-admin/cat.js/p-admin/images.php
/wp-admin/cat.js/wp-admin/images/align-center-2x.png.php
/wp-admin/cat.js/wp-admin/images/align-center.png.php
/wp-admin/cat.js/wp-admin/images/align-left-2x.png.php
/wp-admin/cat.js/wp-admin/images/align-left.png.php
/wp-admin/cat.js/wp-admin/images/align-none-2x.png.php
/wp-admin/cat.js/wp-admin/images/align-none.png.php
/wp-admin/cat.js/wp-admin/images/align-right-2x.png.php
/wp-admin/cat.js/wp-admin/images/align-right.png.php
/wp-admin/cat.js/wp-admin/images/archive-link.png.php
/wp-admin/cat.js/wp-admin/images/arrows-2x.png.php
/wp-admin/cat.js/wp-admin/images/arrows-dark-2x.png.php
/wp-admin/cat.js/wp-admin/images/arrows-dark.png.php
/wp-admin/cat.js/wp-admin/images/arrows-dark-vs-2x.png.php
/wp-admin/cat.js/wp-admin/images/arrows-dark-vs.png.php
/wp-admin/cat.js/wp-admin/images/arrows.png.php
/wp-admin/cat.js/wp-admin/images/arrows-pr-2x.png.php
/wp-admin/cat.js/wp-admin/images/arrows-pr.png.php
/wp-admin/cat.js/wp-admin/images/arrows-vs-2x.png.php
/wp-admin/cat.js/wp-admin/images/arrows-vs.png.php
/wp-admin/cat.js/wp-admin/images/blue-grad.png.php
/wp-admin/cat.js/wp-admin/images/box-bg.gif.php
/wp-admin/cat.js/wp-admin/images/box-bg-left.gif.php
/wp-admin/cat.js/wp-admin/images/box-bg-right.gif.php
/wp-admin/cat.js/wp-admin/images/box-butt.gif.php
/wp-admin/cat.js/wp-admin/images/box-butt-left.gif.php
/wp-admin/cat.js/wp-admin/images/box-head.gif.php
/wp-admin/cat.js/wp-admin/images/box-butt-right.gif.php
/wp-admin/cat.js/wp-admin/images/box-head-left.gif.php
/wp-admin/cat.js/wp-admin/images/box-head-right.gif.php
/wp-admin/cat.js/wp-admin/images/browse-happy.gif.php
/wp-admin/cat.js/wp-admin/images/bubble_bg-2x.gif.php
/wp-admin/cat.js/wp-admin/images/bubble_bg.gif.php
/wp-admin/cat.js/wp-admin/images/bubble_bg-rtl-2x.gif.php
/wp-admin/cat.js/wp-admin/images/bubble_bg-rtl.gif.php
/wp-admin/cat.js/wp-admin/images/button-grad-active.png.php
/wp-admin/cat.js/wp-admin/images/button-grad-active-vs.png.php
/wp-admin/cat.js/wp-admin/images/button-grad.png.php
/wp-admin/cat.js/wp-admin/images/button-grad-vs.png.php
/wp-admin/cat.js/wp-admin/images/comment-grey-bubble-2x.png.php
/wp-admin/cat.js/wp-admin/images/comment-grey-bubble.png.php
/wp-admin/cat.js/wp-admin/images/date-button-2x.gif.php
/wp-admin/cat.js/wp-admin/images/date-button.gif.php
/wp-admin/cat.js/wp-admin/images/ed-bg.gif.php
/wp-admin/cat.js/wp-admin/images/ed-bg-vs.gif.php
/wp-admin/cat.js/wp-admin/images/fade-butt.png.php
/wp-admin/cat.js/wp-admin/images/fav-arrow.gif.php
/wp-admin/cat.js/wp-admin/images/fav-arrow-rtl.gif.php
/wp-admin/cat.js/wp-admin/images/fav-arrow-vs.gif.php
/wp-admin/cat.js/wp-admin/images/fav-arrow-vs-rtl.gif.php
/wp-admin/cat.js/wp-admin/images/fav.png.php
/wp-admin/cat.js/wp-admin/images/fav-top-vs.gif.php
/wp-admin/cat.js/wp-admin/images/fav-vs.png.php
/wp-admin/cat.js/wp-admin/images/generic.png.php
/wp-admin/cat.js/wp-admin/images/gray-grad.png.php
/wp-admin/cat.js/wp-admin/images/icons32-2x.png.php
/wp-admin/cat.js/wp-admin/images/icons32.png.php
/wp-admin/cat.js/wp-admin/images/icons32-vs-2x.png.php
/wp-admin/cat.js/wp-admin/images/icons32-vs.png.php
/wp-admin/cat.js/wp-admin/images/imgedit-icons-2x.png.php
/wp-admin/cat.js/wp-admin/images/imgedit-icons.png.php
/wp-admin/cat.js/wp-admin/images/list-2x.png.php
/wp-admin/cat.js/wp-admin/images/list.png.php
/wp-admin/cat.js/wp-admin/images/list-vs.png.php
/wp-admin/cat.js/wp-admin/images/loading.gif.php
/wp-admin/cat.js/wp-admin/images/loading-publish.gif.php
/wp-admin/cat.js/wp-admin/images/lock-2x.png.php
/wp-admin/cat.js/wp-admin/images/lock.png.php
/wp-admin/cat.js/wp-admin/images/login-bkg-bottom.gif.php
/wp-admin/cat.js/wp-admin/images/login-bkg-tile.gif.php
/wp-admin/cat.js/wp-admin/images/login-header.png.php
/wp-admin/cat.js/wp-admin/images/logo-ghost.png.php
/wp-admin/cat.js/wp-admin/images/logo.gif.php
/wp-admin/cat.js/wp-admin/images/logo-login.gif.php
/wp-admin/cat.js/wp-admin/images/marker.png.php
/wp-admin/cat.js/wp-admin/images/mask.png.php
/wp-admin/cat.js/wp-admin/images/media-button-2x.png.php
/wp-admin/cat.js/wp-admin/images/media-button-image.gif.php
/wp-admin/cat.js/wp-admin/images/media-button-music.gif.php
/wp-admin/cat.js/wp-admin/images/media-button-other.gif.php
/wp-admin/cat.js/wp-admin/images/media-button.png.php
/wp-admin/cat.js/wp-admin/images/media-button-video.gif.php
/wp-admin/cat.js/wp-admin/images/menu-2x.png.php
/wp-admin/cat.js/wp-admin/images/menu-arrows.gif.php
/wp-admin/cat.js/wp-admin/images/menu-bits.gif.php
/wp-admin/cat.js/wp-admin/images/menu-bits-rtl.gif.php
/wp-admin/cat.js/wp-admin/images/menu-bits-rtl-vs.gif.php
/wp-admin/cat.js/wp-admin/images/menu-bits-vs.gif.php
/wp-admin/cat.js/wp-admin/images/menu-dark.gif.php
/wp-admin/cat.js/wp-admin/images/menu-dark-rtl.gif.php
/wp-admin/cat.js/wp-admin/images/menu.png.php
/wp-admin/cat.js/wp-admin/images/menu-shadow.png.php
/wp-admin/cat.js/wp-admin/images/menu-shadow-rtl.png.php
/wp-admin/cat.js/wp-admin/images/menu-vs-2x.png.php
/wp-admin/cat.js/wp-admin/images/menu-vs.png.php
/wp-admin/cat.js/wp-admin/images/no.png.php
/wp-admin/cat.js/wp-admin/images/notice.gif.php
/wp-admin/cat.js/wp-admin/images/post-formats32.png.php
/wp-admin/cat.js/wp-admin/images/post-formats32-vs.png.php
/wp-admin/cat.js/wp-admin/images/post-formats.png.php
/wp-admin/cat.js/wp-admin/images/post-formats-vs.png.php
/wp-admin/cat.js/wp-admin/images/press-this-2x.png.php
/wp-admin/cat.js/wp-admin/images/press-this.png.php
/wp-admin/cat.js/wp-admin/images/required.gif.php
/wp-admin/cat.js/wp-admin/images/resize-2x.gif.php
/wp-admin/cat.js/wp-admin/images/resize.gif.php
/wp-admin/cat.js/wp-admin/images/resize-rtl-2x.gif.php
/wp-admin/cat.js/wp-admin/images/resize-rtl.gif.php
/wp-admin/cat.js/wp-admin/images/screen-options-right.gif.php
/wp-admin/cat.js/wp-admin/images/screen-options-right-up.gif.php
/wp-admin/cat.js/wp-admin/images/se.png.php
/wp-admin/cat.js/wp-admin/images/sort-2x.gif.php
/wp-admin/cat.js/wp-admin/images/sort.gif.php
/wp-admin/cat.js/wp-admin/images/star.gif.php
/wp-admin/cat.js/wp-admin/images/stars-2x.png.php
/wp-admin/cat.js/wp-admin/images/stars.png.php
/wp-admin/cat.js/wp-admin/images/stars-rtl-2x.png.php
/wp-admin/cat.js/wp-admin/images/stars-rtl.png.php
/wp-admin/cat.js/wp-admin/images/toggle-arrow.gif.php
/wp-admin/cat.js/wp-admin/images/toggle-arrow-rtl.gif.php
/wp-admin/cat.js/wp-admin/images/toggle.gif.php
/wp-admin/cat.js/wp-admin/images/visit-site-button-grad.gif.php
/wp-admin/cat.js/wp-admin/images/visit-site-button-grad-vs.gif.php
/wp-admin/cat.js/wp-admin/images/welcome-icons-2x.png.php
/wp-admin/cat.js/wp-admin/images/welcome-icons.png.php
/wp-admin/cat.js/wp-admin/images/wheel.png.php
/wp-admin/cat.js/wp-admin/images/white-grad-active.png.php
/wp-admin/cat.js/wp-admin/images/white-grad.png.php
/wp-admin/cat.js/wp-admin/images/widgets-arrow.gif.php
/wp-admin/cat.js/wp-admin/images/wordpress-logo-2x.png.php
/wp-admin/cat.js/wp-admin/images/wordpress-logo.png.php
/wp-admin/cat.js/wp-admin/images/wp-badge-2x.png.php
/wp-admin/cat.js/wp-admin/images/wp-badge.png.php
/wp-admin/cat.js/wp-admin/images/wp-logo-2x.png.php
/wp-admin/cat.js/wp-admin/images/wp-logo.png.php
/wp-admin/cat.js/wp-admin/images/wp-logo-vs-2x.png.php
/wp-admin/cat.js/wp-admin/images/wp-logo-vs.gif.php
/wp-admin/cat.js/wp-admin/images/wp-logo-vs.png.php
/wp-admin/cat.js/wp-admin/images/wpspin_dark.gif.php
/wp-admin/cat.js/wp-admin/images/wpspin_light-2x.gif.php
/wp-admin/cat.js/wp-admin/images/wpspin_light.gif.php
/wp-admin/cat.js/wp-admin/images/xit-2x.gif.php
/wp-admin/cat.js/wp-admin/images/xit.gif.php
/wp-admin/cat.js/wp-admin/images/yes.png.php
/wp-admin/cat.js/p-admin/import.php
/wp-admin/cat.js/wp-admin/import/blogger.php.php
/wp-admin/cat.js/wp-admin/import/blogware.php.php
/wp-admin/cat.js/wp-admin/import/dotclear.php.php
/wp-admin/cat.js/wp-admin/import/greymatter.php.php
/wp-admin/cat.js/wp-admin/import/livejournal.php.php
/wp-admin/cat.js/wp-admin/import/mt.php.php
/wp-admin/cat.js/wp-admin/import.php.php
/wp-admin/cat.js/wp-admin/import/rss.php.php
/wp-admin/cat.js/wp-admin/import/textpattern.php.php
/wp-admin/cat.js/wp-admin/import/wordpress.php.php
/wp-admin/cat.js/p-admin/includes.php
/wp-admin/cat.js/wp-admin/includes/ajax-actions.php.php
/wp-admin/cat.js/wp-admin/includes/admin.php.php
/wp-admin/cat.js/wp-admin/includes/bookmark.php.php
/wp-admin/cat.js/wp-admin/includes/class-ftp.php.php
/wp-admin/cat.js/wp-admin/includes/class-ftp-pure.php.php
/wp-admin/cat.js/wp-admin/includes/class-ftp-sockets.php.php
/wp-admin/cat.js/wp-admin/includes/class-pclzip.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-comments-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-filesystem-base.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-filesystem-direct.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-filesystem-ftpsockets.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-filesystem-ftpext.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-filesystem-ssh2.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-importer.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-links-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-media-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-ms-sites-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-ms-themes-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-ms-users-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-plugin-install-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-plugins-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-posts-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-terms-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-theme-install-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-upgrader.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-themes-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/class-wp-users-list-table.php.php
/wp-admin/cat.js/wp-admin/includes/comment.php.php
/wp-admin/cat.js/wp-admin/includes/continents-cities.php.php
/wp-admin/cat.js/wp-admin/includes/dashboard.php.php
/wp-admin/cat.js/wp-admin/includes/deprecated.php.php
/wp-admin/cat.js/wp-admin/includes/export.php.php
/wp-admin/cat.js/wp-admin/includes/file.php.php
/wp-admin/cat.js/wp-admin/includes/image-edit.php.php
/wp-admin/cat.js/wp-admin/includes/image.php.php
/wp-admin/cat.js/wp-admin/includes/import.php.php
/wp-admin/cat.js/wp-admin/includes/list-table.php.php
/wp-admin/cat.js/wp-admin/includes/manifest.php.php
/wp-admin/cat.js/wp-admin/includes/media.php.php
/wp-admin/cat.js/wp-admin/includes/menu.php.php
/wp-admin/cat.js/wp-admin/includes/meta-boxes.php.php
/wp-admin/cat.js/wp-admin/includes/misc.php.php
/wp-admin/cat.js/wp-admin/includes/ms-deprecated.php.php
/wp-admin/cat.js/wp-admin/includes/ms.php.php
/wp-admin/cat.js/wp-admin/includes/nav-menu.php.php
/wp-admin/cat.js/wp-admin/includes/plugin-install.php.php
/wp-admin/cat.js/wp-admin/includes/plugin.php.php
/wp-admin/cat.js/wp-admin/includes/post.php.php
/wp-admin/cat.js/wp-admin/includes/revision.php.php
/wp-admin/cat.js/wp-admin/includes/schema.php.php
/wp-admin/cat.js/wp-admin/includes/screen.php.php
/wp-admin/cat.js/wp-admin/includes/taxonomy.php.php
/wp-admin/cat.js/wp-admin/includes/template.php.php
/wp-admin/cat.js/wp-admin/includes/theme-install.php.php
/wp-admin/cat.js/wp-admin/includes/theme.php.php
/wp-admin/cat.js/wp-admin/includes/update-core.php.php
/wp-admin/cat.js/wp-admin/includes/update.php.php
/wp-admin/cat.js/wp-admin/includes/upgrade.php.php
/wp-admin/cat.js/wp-admin/includes/user.php.php
/wp-admin/cat.js/wp-admin/includes/widgets.php.php
/wp-admin/cat.js/wp-admin/index-extra.php.php
/wp-admin/cat.js/wp-admin/index.php.php
/wp-admin/cat.js/wp-admin/install.css.php
/wp-admin/cat.js/wp-admin/install-helper.php.php
/wp-admin/cat.js/wp-admin/install.php.php
/wp-admin/cat.js/wp-admin/install-rtl.css.php
/wp-admin/cat.js/p-admin/js.php
/wp-admin/cat.js/wp-admin/js/accordion.js.php
/wp-admin/cat.js/wp-admin/js/accordion.min.js.php
/wp-admin/cat.js/wp-admin/js/cat.dev.js.php
/wp-admin/cat.js/wp-admin/js/categories.dev.js.php
/wp-admin/cat.js/wp-admin/js/categories.js.php
/wp-admin/cat.js/wp-admin/js/categories.min.js.php
/wp-admin/cat.js/wp-admin/js/cat.js.php
/wp-admin/cat.js/wp-admin/js/cat.min.js.php
/wp-admin/cat.js/wp-admin/js/color-picker.js.php
/wp-admin/cat.js/wp-admin/js/color-picker.min.js.php
/wp-admin/cat.js/wp-admin/js/comment.dev.js.php
/wp-admin/cat.js/wp-admin/js/comment.js.php
/wp-admin/cat.js/wp-admin/js/comment.min.js.php
/wp-admin/cat.js/wp-admin/js/common.dev.js.php
/wp-admin/cat.js/wp-admin/js/common.js.php
/wp-admin/cat.js/wp-admin/js/custom-background.dev.js.php
/wp-admin/cat.js/wp-admin/js/common.min.js.php
/wp-admin/cat.js/wp-admin/js/custom-background.js.php
/wp-admin/cat.js/wp-admin/js/custom-background.min.js.php
/wp-admin/cat.js/wp-admin/js/custom-fields.dev.js.php
/wp-admin/cat.js/wp-admin/js/custom-fields.js.php
/wp-admin/cat.js/wp-admin/js/custom-fields.min.js.php
/wp-admin/cat.js/wp-admin/js/custom-header.js.php
/wp-admin/cat.js/wp-admin/js/customize-controls.js.php
/wp-admin/cat.js/wp-admin/js/customize-controls.min.js.php
/wp-admin/cat.js/wp-admin/js/dashboard.dev.js.php
/wp-admin/cat.js/wp-admin/js/dashboard.js.php
/wp-admin/cat.js/wp-admin/js/dashboard.min.js.php
/wp-admin/cat.js/wp-admin/js/edit-comments.dev.js.php
/wp-admin/cat.js/wp-admin/js/edit-comments.js.php
/wp-admin/cat.js/wp-admin/js/edit-comments.min.js.php
/wp-admin/cat.js/wp-admin/js/editor.dev.js.php
/wp-admin/cat.js/wp-admin/js/editor.js.php
/wp-admin/cat.js/wp-admin/js/editor.min.js.php
/wp-admin/cat.js/wp-admin/js/farbtastic.js.php
/wp-admin/cat.js/wp-admin/js/gallery.dev.js.php
/wp-admin/cat.js/wp-admin/js/gallery.js.php
/wp-admin/cat.js/wp-admin/js/gallery.min.js.php
/wp-admin/cat.js/wp-admin/js/image-edit.dev.js.php
/wp-admin/cat.js/wp-admin/js/image-edit.js.php
/wp-admin/cat.js/wp-admin/js/image-edit.min.js.php
/wp-admin/cat.js/wp-admin/js/inline-edit-post.dev.js.php
/wp-admin/cat.js/wp-admin/js/inline-edit-post.js.php
/wp-admin/cat.js/wp-admin/js/inline-edit-post.min.js.php
/wp-admin/cat.js/wp-admin/js/inline-edit-tax.dev.js.php
/wp-admin/cat.js/wp-admin/js/inline-edit-tax.js.php
/wp-admin/cat.js/wp-admin/js/inline-edit-tax.min.js.php
/wp-admin/cat.js/wp-admin/js/iris.min.js.php

Files found with a 200 responce:

/wp-content/uploads/flags/es.svg
/wp-content/uploads/flags/jp.svg
/wp-content/uploads/flags/sa.svg
/wp-content/uploads/flags/kr.svg
/wp-content/uploads/flags/ru.svg
/wp-content/uploads/flags/vn.svg
/wp-content/uploads/flags/cn.svg
/wp-content/uploads/flags/ua.svg
/wp-content/uploads/flags/th.svg
/wp-content/themes/bridge-child/assets/svg-icons/app-store-badge.svg
/wp-content/themes/bridge-child/assets/svg-icons/google-play-badge.svg
/wp-admin/js/word-count.js/wp-admin/css/media-rtl.dev.css.php
/wp-admin/js/word-count.js/wp-admin/css/media-rtl.min.css.php
/wp-admin/js/word-count.js/wp-admin/css/ms.dev.css.php
/wp-admin/js/word-count.js/wp-admin/css/nav-menu.css.php
/wp-admin/js/image-edit.dev.js/wp-admin/edit-link-form.php.php
/wp-admin/js/word-count.js/wp-admin/css/media-rtl.css.php
/wp-admin/js/word-count.js/wp-admin/css/ms.css.php
/wp-admin/js/customize-controls.js/wp-admin/images/arrows-2x.png.php
/wp-admin/js/inline-edit-post.dev.js/wp-admin/freedoms.php.php
/wp-admin/js/edit-comments.min.js/p-admin/images.php
/wp-admin/js/theme-preview.dev.js/wp-admin/css/plugin-install.css.php
/wp-admin/network/freedoms.php/wp-admin/credits.php.php
/wp-admin/js/editor.dev.js/wp-admin/images/arrows-dark-2x.png.php
/wp-admin/js/farbtastic.js/wp-admin/images/blue-grad.png.php
/wp-admin/js/custom-background.min.js/wp-admin/images/box-head.gif.php
/wp-admin/js/editor.dev.js/wp-admin/images/arrows-2x.png.php
/wp-admin/includes/class-wp-filesystem-ftpext.php/wp-admin/images/post-formats-vs.png.php
/wp-admin/js/categories.dev.js/wp-admin/images/comment-grey-bubble.png.php
/wp-admin/js/categories.dev.js/wp-admin/images/comment-grey-bubble-2x.png.php
/wp-admin/js/custom-background.min.js/wp-admin/images/box-butt-left.gif.php
/wp-admin/includes/class-wp-importer.php/wp-admin/images/lock.png.php
/wp-admin/js/custom-background.dev.js/wp-admin/images/align-right-2x.png.php
/wp-admin/js/farbtastic.js/wp-admin/images/box-bg.gif.php
/wp-admin/js/custom-background.min.js/wp-admin/images/box-butt-right.gif.php
/wp-admin/includes/class-wp-ms-themes-list-table.php/wp-admin/images/login-header.png.php
/wp-admin/includes/class-wp-filesystem-ftpext.php/wp-admin/images/post-formats.png.php
/wp-admin/includes/class-wp-filesystem-ftpext.php/wp-admin/images/press-this-2x.png.php
/wp-admin/includes/continents-cities.php/wp-admin/images/list-2x.png.php
/wp-admin/js/categories.dev.js/wp-admin/images/button-grad-vs.png.php
/wp-admin/includes/theme.php/wp-admin/images/lock-2x.png.php
/wp-admin/js/custom-header.js/wp-admin/edit-link-form.php.php


--------------------------------
